{{- if .Values.web.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: web
type: Opaque
stringData:
  {{- range $key, $value := .Values.web.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
