apiVersion: v2
name: geoserver-cloud
description: Helm chart for deploying GeoServer Cloud (gateway, webui, rest, wms, wfs, wcs, gwc, rabbitmq) in Kubernetes
type: application
version: 0.1.0
appVersion: "v1.16.0"
maintainers:
  - name: WEDO
    email: TODO@momrah.gov.sa
