name: baladyeye-widgets-app
namespace: urbi
replicaCount: 1

image: registry.momrah.gov.sa/urbi-omar/baladyeye-widgets-app-stg:v0.02
containerPort: 80
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "1"
    memory: "1000Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

ingress:
  name: be-baladyeye-widgets-app
  host: baladyeye-stg.momah.gov.sa

