name: short-link
namespace: urbi
replicaCount: 1

image: registry.momrah.gov.sa/urbi-omar/short-link:v0.0.3
containerPort: 3000
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"

env:
  
  REDIS_CLUSTER_ENABLED: "true"
  REDIS_HOSTNAME: "redis-redis-cluster"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "CVb7saZB4Rtu"
  REDIS_USERNAME: "default"
  NODE_ENV: "development"
# PostgreSQL
  DB_HOST: "10.96.207.56"
  DB_PORT: "5000"
  DB_NAME: "balady"
  DB_USER: "balady"
  DB_PASSWORD: "zHrqQqaZnyxn8roNsPzfhrmxk6a1v2Vf"
  DB_SCHEMA: "public"
# Short URL Domain
  SHORT_URL_DOMAIN: "https://urbi-lifestyle-stg.momrah.gov.sa"
# Target Domain (safelist)
  TARGET_DOMAIN: "https://plus.balady.sa"
# Rate Limiting
  RATE_LIMIT_CREATE: "100"
  RATE_LIMIT_READ: "1000"
  RATE_LIMIT_WINDOW_MS: "60000"
# Cache TTL (seconds)
  CACHE_TTL: "43200"


# env:
#   API_KEY: "7945b9d8-1e95-4c1b-8886-d6a4c6c69e73"
#   REDIS_CLUSTER_ENABLED: "true"
#   REDIS_HOSTNAME: "redis-redis-cluster"
#   REDIS_PORT: "6379"
#   REDIS_PASSWORD: "CVb7saZB4Rtu"
#   REDIS_USERNAME: "default"
#   NODE_ENV: "development"
# # PostgreSQL
#   DB_HOST: "10.246.3.65"
#   DB_PORT: "5432"
#   DB_NAME: "balady"
#   DB_USER: "balady"
#   DB_PASSWORD: "QE79ujmp3fw2eYV363GcDLh0zuVOFpaZ"
#   DB_SCHEMA: "public"
# # Short URL Domain
#   SHORT_URL_DOMAIN: "https://urbi-lifestyle-stg.momrah.gov.sa"
# # Target Domain (safelist)
#   TARGET_DOMAIN: "https://plus.balady.sa"
# # Rate Limiting
#   RATE_LIMIT_CREATE: "100"
#   RATE_LIMIT_READ: "1000"
#   RATE_LIMIT_WINDOW_MS: "60000"
# # Cache TTL (seconds)
#   CACHE_TTL: "43200"

# Ingress configuration for production
ingress:
  name: short-link
  className: urbi
  host: urbi-lifestyle-stg.momrah.gov.sa

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token,x-api-key"
    nginx.ingress.kubernetes.io/rewrite-target: "$2"

  # Path rules
  paths:
    - path: /1.0/short(/|$)(.*)
      pathType: ImplementationSpecific
      backend: short-link
