apiVersion: v1
kind: Service
metadata:
  name: maplocator-snapshot-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}

