apiVersion: v2
dependencies:
- alias: geoserver
  name: application
  repository: https://camptocamp.github.io/helm-application/
  version: 2.17.1
description: A Helm chart for Geoserver-cloud
name: geoservercloud
version: 2.5.3
