# Release metadata
name: rcmc-markers-api
namespace: urbi
replicaCount: 6

# Docker image (production tag)
image: registry.momrah.gov.sa/urbi-omar/rcmc-markers-api:v0.6
containerPort: 80
servicePort: 80
serviceType: ClusterIP

# Resource requests & limits
resources:
  limits:
    cpu: "1"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "128Mi"

# Non-sensitive environment variables (ConfigMap)
env:
  DB_IP: "10.246.3.65"
  DB_PORT: "5432"
  DB_NAME: "db_rcmc_hajj25"
  DB_USER: "rcmc_admin"
  LOG_LEVEL: "info"
  CERT_FILE: "CaCertificate-prod-jed-urbi-postgresql.pub"
  HOST: "0.0.0.0"
  PORT: "3000"

# Sensitive environment variables (Secret)
secret:
  DB_PASSWORD: "Rg9@2025!Geo#DbSecure"

# Ingress configuration for production
ingress:
  name: be-rcmc-markers-api
  className: urbi
  host: urbi-lifestyle.momrah.gov.sa

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Original-URI $request_uri;

  # Path rules
  paths:
    - path: /1\.0/rcmc-markers$
      backend: rcmc-markers-api
    - path: /1\.0/rcmc-area$
      backend: rcmc-markers-api
    - path: /1\.0/rcmc-markers/byId$
      backend: rcmc-markers-api

