{{- if .Values.ingress }}
{{- $ing := .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ing.name }}
  namespace: {{ (index $.Values "geoserver-gateway").namespace }}
  annotations:
    {{- range $key, $value := $ing.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ $ing.className }}
  rules:
    - host: {{ $ing.host }}
      http:
        paths:
          {{- range $ing.paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .backend }}
                port:
                  number: {{ (index $.Values .backend).servicePort }}
          {{- end }}
{{- end }}
---
{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ (index $.Values "geoserver-gateway").namespace }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
{{- end }}