name: cityview-ump-api
namespace: urbi
replicaCount: 1

image: registry.momrah.gov.sa/urbi-omar/cityview-ump-api:v0.1.9
containerPort: 3000
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"

# Ingress configuration for production
ingress:
  name: be-cityview-ump-api
  className: urbi
  host: cityview-pro-ump.momah.gov.sa

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"

  # Path rules
  paths:
    - path: /ump-api(/|$)(.*)
      backend: cityview-ump-api

