name: cityview-ump-ui
namespace: urbi
replicaCount: 1

image: registry.momrah.gov.sa/urbi-omar/cityview-ump-ui:v0.1.25
containerPort: 80
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"
env:
  #VITE_API_BASE_URL: http://cityview-pro-ump.momah.gov.sa/ump-api/
  #VITE_AUTH_API_BASE_URL: https://cityview.wedo.solutions:3000/api
  VITE_APP_NAME: User Management System
  VITE_APP_VERSION: 1.0.0
  VITE_API_BASE_URL: https://cityview-pro-ump.momah.gov.sa/ump-api
  VITE_AUTH_API_BASE_URL: https://cityview.wedo.solutions:3000/api
  VITE_SOCKET_URL: https://cityview.wedo.solutions:3000
  VITE_SOCKET_PATH: /ws
  VITE_REDIRECT_URL: /permissions
  VITE_WS_URL: https://cityview.wedo.solutions:3000


# Ingress configuration for production
ingress:
  name: be-cityview-ump-ui
  className: urbi
  host: cityview-pro-ump.momah.gov.sa

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"

  # Path rules
  paths:
    - path: /ump(/|$)(.*)
      backend: cityview-ump-ui

