apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AI_URL_TOKEN: {{ .Values.secret.AI_URL_TOKEN }}
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD }}

