apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
type: Opaque
data:
{{- range $key, $val := .Values.secret }}
  {{ $key }}: "{{ $val | b64enc }}"
{{- end }}
