airflowVersion: "3.1.8"
executor: KubernetesExecutor

fernetKey: "b1RPYzdTOFpRMXZ6cFJFakxLZ3pqbFNSRzk3V2tRbFo="

postgresql:
  enabled: false

pgbouncer:
  enabled: true

data:
  metadataConnection:
    user:     airflow_admin_3
    pass:     VeryStrongPassword!123
    protocol: postgresql
    host:     10.246.3.65
    port:     5432
    db:       airflow-3
    sslmode:  "require"
  # resultBackendConnection:     # optional

airflow:
  config:
    AIRFLOW_API_BASE_URL: "https://cityview-airflow.momah.gov.sa"

config:
  core:
    max_active_tasks_per_dag: 200
    parallelism:              500
    default_pool_task_slot_count: 500
  database:
    sql_alchemy_pool_enabled: 'True'
    sql_alchemy_pool_size: 50
    sql_alchemy_pool_recycle: 1800
    sql_alchemy_max_overflow: 80
    sql_alchemy_pool_pre_ping: 'True'
    sql_alchemy_pool_timeout: 60

  api:
    secret_key: "16f143ec4690e48710cbe27914d2a115dcb16c92e1441206815d09bc93bf5c60"
    base_url: "https://cityview-airflow.momah.gov.sa"
    auth_backends: "airflow.providers.fab.auth_manager.api.auth.backend.fab_auth"
    client_request_timeout: 60

  api_auth:
    jwt_secret: "16f143ec4690e48710cbe27914d2a115dcb16c92e1441206815d09bc93bf5c60"
    jwt_algorithm: "HS256"

  kubernetes_executor:
    delete_worker_pods:     'False'

  logging:
    remote_logging:         'True'
    logging_level:          INFO
    remote_base_log_folder: 's3://prod-airflow-logging-xcom/logs'
    remote_log_conn_id:     oci_s3_conn
    encrypt_s3_logs:        'False'

  aws:
    s3_use_sigv4: 'True'
    signature_version: 's3v4'

extraEnv: |
  - name: AIRFLOW_CONN_OCI_S3_CONN
    value: 'aws://8b27cd27701b5cacb854d684d00a4e407d0ee75a:%2Be8IrLxwqNdHR0s4SbHKTANaeos7KD22QK%2F1SMV7qzo%3D@?endpoint_url=https%3A%2F%2Faxownvq9lhmx.compat.objectstorage.me-jeddah-1.oraclecloud.com&region_name=me-jeddah-1'
  - name: AWS_ACCESS_KEY_ID
    value: '8b27cd27701b5cacb854d684d00a4e407d0ee75a'
  - name: AWS_SECRET_ACCESS_KEY
    value: '+e8IrLxwqNdHR0s4SbHKTANaeos7KD22QK/1SMV7qzo='
  - name: AWS_DEFAULT_REGION
    value: 'me-jeddah-1'
  - name: AWS_S3_ADDRESSING_STYLE
    value: 'path'
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: 'oci_s3_conn'
  - name: AIRFLOW__CORE__XCOM_BACKEND
    value: 'airflow.providers.common.io.xcom.backend.XComObjectStorageBackend'
  - name: AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_PATH
    value: 's3://prod-airflow-logging-xcom/xcom'
  - name: AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_THRESHOLD
    value: '1048576'
  - name: AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_COMPRESSION
    value: 'zip'

airflowLocalSettings: |-
  import os
  from pathlib import Path

  AIRFLOW_HOME = Path(os.environ.get("AIRFLOW_HOME", "~/airflow")).expanduser()
  BASE_LOG_FOLDER = os.environ.get("AIRFLOW__LOGGING__BASE_LOG_FOLDER", f"{AIRFLOW_HOME}/logs")

  LOGGING_CONFIG = {
      'version': 1,
      'disable_existing_loggers': False,
      'formatters': {
          'airflow': {
              'format': '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s'
          },
      },
      'handlers': {
          'console': {
              'class': 'logging.StreamHandler',
              'formatter': 'airflow',
              'stream': 'ext://sys.stdout'
          },
          'task': {
              'class': 'logging.StreamHandler',
              'formatter': 'airflow',
              'stream': 'ext://sys.stdout'
          },
      },
      'loggers': {
          'airflow': {
              'handlers': ['console'],
              'level': 'INFO',
              'propagate': False
          },
          'airflow.task': {
              'handlers': ['task'],
              'level': 'INFO',
              'propagate': False,
          },
      },
      'root': {
          'handlers': ['console'],
          'level': 'INFO',
      }
  }

images:
  airflow:
    repository: registry.momrah.gov.sa/urbi-omar/momah-airflow
    tag:        "3.1.8-python3.12-03"
    pullPolicy: IfNotPresent
  useDefaultImageForMigration: false
  statsd:
    repository: quay.io/prometheus/statsd-exporter
    tag:        "v0.28.0"
    pullPolicy: IfNotPresent
  redis:
    repository: redis
    tag:        "7.2-bookworm"
    pullPolicy: IfNotPresent
  gitSync:
    repository: registry.k8s.io/git-sync/git-sync
    tag:        "v4.3.0"
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  apiServer:
    enabled:          true
    host:             cityview-airflow.momah.gov.sa
    ingressClassName: urbi
    pathType:         ImplementationSpecific
    path:             /
    tls:
      enabled:        false

workers:
  # KubernetesExecutor: this block defines the resource template for task pods
  resources:
    requests:
      cpu:    "500m"
      memory: "1Gi"
    limits:
      cpu:    "4000m"
      memory: "4Gi"
  serviceAccount:
    create:                       true
    automountServiceAccountToken: true

scheduler:
  enabled: true
  replicas: 3
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
    limits:
      cpu: "4000m"
      memory: "16Gi"
  waitForMigrations:
    enabled: true

apiServer:
  replicas: 3
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

dagProcessor:
  enabled: true
  replicas: 2
  resources:
    requests:
      cpu: "2000m"
      memory: "1Gi"
    limits:
      cpu: "4000m"
      memory: "2Gi"
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 10
    periodSeconds: 60

webserver:
  defaultUser:
    enabled:   true
    role:      Admin
    username:  af_admin
    email:     app.services@wedosolutions.sa
    firstName: Airflow
    lastName:  Admin
    password:  "OmarK@#$1998"

triggerer:
  enabled: true
  replicas: 2
  persistence:
    enabled: true
    size:    50Gi

dags:
  gitSync:
    enabled: true
    repo:    https://github.com/WEDO-SOLUTIONS/momah-cityview-airflow-dags.git
    branch:  main
    rev:     HEAD
    subPath: dags
    period:  30s
  persistence:
    enabled: false

cleanup:
  enabled:  true
  schedule: '*/15 * * * *'
  command:  null
  args:
    - bash
    - '-c'
    - 'exec airflow kubernetes cleanup-pods --namespace={{ .Release.Namespace }}'
