name: zero-project-ai
namespace: urbi
replicaCount: 1
appVersion: development

image: REPLACE_IMAGE
imagePullPolicy: IfNotPresent
containerPort: 8000
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "12"
    memory: "16Gi"
  requests:
    cpu: "4"
    memory: "8Gi"

healthCheck:
  readiness:
    path: /health
  liveness:
    path: /health

env:
  - name: MONGO_DB_URL
    value: "mongodb://localhost:27017"
  - name: MONGO_DB_NAME
    value: "mcif-mongodb"

ingress:
  name: be-zero-project-ai
  host: REPLACE_HOST
  className: urbi
  corsAllowHeaders: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token
  proxyReadTimeout: "300"
  paths:
    - path: /mcifai(/|$)(.*)
      pathType: ImplementationSpecific

mongodb:
  enabled: false
  name: mongo-zero-project-ai
  image: mongo:7.0
  initDatabase: mcif-mongodb
  resources:
    limits:
      cpu: "8"
      memory: "8096Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  pvc:
    create: false
    name: mongodb-pvc-zero-project-ai
    size: "10Gi"
    accessMode: ReadWriteOnce

