name: zero-project-ai
namespace: urbi
replicaCount: 1
appVersion: development

image: registry.momrah.gov.sa/urbi-omar/zero-project-ai:v0.0.4
imagePullPolicy: IfNotPresent
containerPort: 8000
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "12"
    memory: "16Gi"
  requests:
    cpu: "4"
    memory: "8Gi"

healthCheck:
  readiness:
    path: /api/health
  liveness:
    path: /api/health

env:
  - name: MONGO_DB_URL
    value: "mongodb://mongo-zero-project-ai:27017"
  - name: MONGO_DB_NAME
    value: "mcif-mongodb"

ingress:
  name: be-zero-project-ai
  host: cityview.momah.gov.sa
  className: urbi
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"
    nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  paths:
    - path: /api/chat
      pathType: ImplementationSpecific
    - path: /api/admin
      pathType: ImplementationSpecific

mongodb:
  enabled: true
  name: mongo-zero-project-ai
  image: mongo:7.0
  initDatabase: mcif-mongodb
  resources:
    limits:
      cpu: "8"
      memory: "8096Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  pvc:
    create: true
    name: mongodb-pvc-zero-project-ai
    size: "10Gi"
    accessMode: ReadWriteOnce

