{{- $middlewareHost := printf "%s.%s.svc.cluster.local" .Values.name .Values.namespace }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.ingress.name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Values.ingress.name }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- if .Values.ingress.serverSnippet }}
    nginx.ingress.kubernetes.io/server-snippet: |
{{ .Values.ingress.serverSnippet | replace "__MIDDLEWARE_HOST__" $middlewareHost | indent 6 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.defaultBackendService }}
                port:
                  number: {{ .Values.ingress.defaultBackendPort }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
