apiVersion: batch/v1
kind: CronJob
metadata:
  name: ow-reporting
spec:
  schedule: "0 9 * * 1"  # Runs at 9 AM every Monday (0 minute, 9 hour, every Monday)
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: ow-reporting
            image: registry.momrah.gov.sa/urbi-omar/ow-reporting-s3:v015
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "8Gi"
                cpu: "500m"
